name: p6docking38_cpu
channels:
  - pytorch
  - https://conda.graylab.jhu.edu
  - pyg
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - biopython=1.78
  - e3nn=0.5.1
  - fair-esm=2.0.0
  - python=3.8.18
  - panel=0.14.0
  - panel-chemistry=0.2.2
  - rdkit=2023.03.3
  - plip=2.3.0
  - prody=2.4.0
  - pyg=2.5.2
  - pymol-open-source=2.5.0
  - pyrosetta
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytorch-scatter=2.1.1
  - pytorch_cluster=1.6.1
  - pytorch_geometric=2.5.3
